### ISSUE TITLE
Some users have broken profiles

### ISSUE THREAD

**Issue by liamdugan** [kirubarajan/roft#177]
For example, user http://roft.io/profile/totally_not_a_robot/ has 257 points on the leaderboard

<img width="469" alt="スクリーンショット 2021-09-07 12 58 18" src="https://user-images.githubusercontent.com/14120375/132383087-3750580b-3764-4bc0-a9f0-5460a5e6afb5.png">

However, their profile says 0 points with no games played
<img width="1024" alt="スクリーンショット 2021-09-07 12 58 25" src="https://user-images.githubusercontent.com/14120375/132383147-755cef22-78ef-4773-ac60-5a2b6c74d972.png">

This same bug also happens for this user:
http://roft.io/profile/Robots>Humans/

But interestingly, not these users:
http://roft.io/profile/lord_ne/
http://roft.io/profile/jo-ral/

**Comment by liamdugan** [comment]
According to artemis it looks like this user https://roft.io/profile/Meggie/ also has this issue

**Comment by daphnei** [comment]
Did you notice this problem by clicking usernames from the leaderboard? 

If so, the main way this could happen is if a person's username was an email address (meggie@gmail.com for example). The leaderboard will show the scrubbed version of their username (just `meggie`), and when you click on it, it will try to go to the profile for `meggie`, not go to the profle for `meggie@gmail.com` as it should. 

We can solve this for future users by using  a regex to prevent them from creating usernames that are email addresses so that no leaderboard scrubbing needs to happen.
